name: ORS_stations
channels:
  - conda-forge
dependencies:
  - python == 3.11
  - pip
  - folium
  - pandas
  - geopandas
  - shapely
  - fiona
  - requests
  - geopandas
  - ipywidgets
  - ipykernel
  - jupytext
  - pyproj
  - jupyter